### ISSUE TITLE
Unexpected ')' on line 117 of run_annoqtl.R

### ISSUE THREAD

**Issue by dence** [gact/shmootl#1]
Hi, I tried to install shmootl via R terminal and got this error:
"/private/var/folders/1_/82hb3kwx2sgf5s04hyrt33gc0000gq/T/RtmpzUrEIK/R.INSTALL2a9266c3a644/shmootl/R/run_annoqtl.R:117:50: unexpected ')'
116:                     # Write updated QTL intervals to temp file.
117:                     if (length(qtl.features) > 0))
                                                      ^
ERROR: unable to collate and parse R files for package ‘shmootl’"

Upon inspection of run_annonqtl.R, it does appear there is an extra ")" in line 117. I'd be happy to fix this myself via pull request. 

Regards,
Daniel Ence

**Comment by tw164** [comment]
That would be great, thanks. A pull request would be most welcome.

**Comment by yh214** [comment]
Fixed. Nice catch Daniel.
